// 예비중등 필수영단어 1000 (데이터 통합본)
var wordData = {
    // ★ 1-2학년 (기초: Day 1 ~ Day 7)
    "1-2": [
        {word:"start", mean:"시작하다"}, {word:"heart", mean:"마음"}, {word:"understand", mean:"이해하다"},
        {word:"cousin", mean:"사촌"}, {word:"write", mean:"쓰다"}, {word:"pants", mean:"바지"},
        {word:"park", mean:"공원"}, {word:"dirty", mean:"더러운"}, {word:"prince", mean:"왕자"},
        {word:"quick", mean:"빠른"}, {word:"beautiful", mean:"아름다운"}, {word:"help", mean:"돕다"},
        {word:"ground", mean:"땅"}, {word:"train", mean:"열차"}, {word:"street", mean:"거리"},
        {word:"side", mean:"측면"}, {word:"job", mean:"직업"}, {word:"week", mean:"일주일"},
        {word:"quiet", mean:"조용히"}, {word:"hear", mean:"듣다"}, {word:"glad", mean:"기쁜"},
        {word:"problem", mean:"문제"}, {word:"young", mean:"젊은"}, {word:"need", mean:"필요하다"},
        {word:"fact", mean:"사실"}, {word:"walk", mean:"걷다"}, {word:"light", mean:"빛"},
        {word:"stand", mean:"서다"}, {word:"parent", mean:"부모"}, {word:"catch", mean:"잡다"},
        {word:"chance", mean:"기회"}, {word:"wake", mean:"깨다"}, {word:"middle", mean:"중간의"},
        {word:"busy", mean:"바쁜"}, {word:"go", mean:"가다"}, {word:"lead", mean:"이끌다"},
        {word:"look", mean:"보다"}, {word:"church", mean:"교회"}, {word:"cloud", mean:"구름"},
        {word:"number", mean:"숫자"}, {word:"dream", mean:"꿈"}, {word:"flag", mean:"국기"},
        {word:"farm", mean:"농장"}, {word:"fly", mean:"날다"}, {word:"say", mean:"말하다"},
        {word:"meat", mean:"고기"}, {word:"month", mean:"달"}, {word:"roof", mean:"지붕"},
        {word:"visit", mean:"방문하다"}, {word:"land", mean:"땅"}, {word:"high", mean:"높은"},
        {word:"vegetable", mean:"야채"}, {word:"angry", mean:"화난"}, {word:"mouse", mean:"쥐"},
        {word:"airport", mean:"공항"}, {word:"long", mean:"긴"}, {word:"little", mean:"작은"},
        {word:"desk", mean:"책상"}, {word:"fun", mean:"재미있는"}, {word:"wet", mean:"젖은"},
        {word:"eat", mean:"먹다"}, {word:"age", mean:"나이"}, {word:"music", mean:"음악"},
        {word:"wife", mean:"아내"}, {word:"cold", mean:"추운"}, {word:"ride", mean:"타다"},
        {word:"wind", mean:"바람"}, {word:"warm", mean:"따뜻한"}, {word:"die", mean:"죽다"},
        {word:"hard", mean:"열심히"}, {word:"work", mean:"일하다"}, {word:"kill", mean:"죽이다"},
        {word:"play", mean:"놀다"}, {word:"sound", mean:"소리"}, {word:"garden", mean:"정원"},
        {word:"travel", mean:"여행"}, {word:"hungry", mean:"배고픈"}, {word:"breakfast", mean:"아침식사"},
        {word:"wait", mean:"기다리다"}, {word:"picture", mean:"사진"}, {word:"winter", mean:"겨울"},
        {word:"round", mean:"둥근"}, {word:"enter", mean:"들어가다"}, {word:"firefighter", mean:"소방관"},
        {word:"north", mean:"북쪽"}, {word:"give", mean:"주다"}, {word:"grass", mean:"풀"},
        {word:"bad", mean:"나쁜"}, {word:"way", mean:"방법"}, {word:"class", mean:"수업"},
        {word:"fruit", mean:"과일"}, {word:"hit", mean:"치다"}, {word:"early", mean:"일찍"},
        {word:"great", mean:"훌륭한"}, {word:"basketball", mean:"농구"}, {word:"real", mean:"진짜의"},
        {word:"large", mean:"큰"}, {word:"half", mean:"절반"}, {word:"bookstore", mean:"서점"},
        {word:"new", mean:"새로운"}, {word:"feel", mean:"느끼다"}, {word:"strong", mean:"강한"},
        {word:"run", mean:"달리다"}, {word:"earth", mean:"지구"}, {word:"make", mean:"만들다"},
        {word:"teach", mean:"가르치다"}, {word:"weak", mean:"약한"}, {word:"right", mean:"옳은"},
        {word:"drink", mean:"마시다"}, {word:"ago", mean:"이전"}, {word:"have", mean:"가지다"},
        {word:"fall", mean:"가을"}, {word:"short", mean:"짧은"}, {word:"group", mean:"단체"},
        {word:"beach", mean:"해변"}, {word:"glass", mean:"유리"}, {word:"mask", mean:"가면"},
        {word:"line", mean:"선"}, {word:"dictionary", mean:"사전"}, {word:"twin", mean:"쌍둥이"}
    ],

    // ★ 3-4학년 (중급: Day 8 ~ Day 13)
    "3-4": [
        {word:"tea", mean:"차"}, {word:"hospital", mean:"병원"}, {word:"cover", mean:"덮다"},
        {word:"TRUE", mean:"진실한"}, {word:"always", mean:"항상"}, {word:"city", mean:"도시"},
        {word:"free", mean:"자유로운"}, {word:"world", mean:"세계"}, {word:"east", mean:"동쪽"},
        {word:"last", mean:"지난"}, {word:"sign", mean:"신호"}, {word:"weather", mean:"날씨"},
        {word:"floor", mean:"바닥"}, {word:"end", mean:"끝"}, {word:"yesterday", mean:"어제"},
        {word:"sight", mean:"시야"}, {word:"sand", mean:"모래"}, {word:"learn", mean:"배우다"},
        {word:"many", mean:"많은"}, {word:"magic", mean:"마술"}, {word:"wash", mean:"씻다"},
        {word:"clean", mean:"깨끗한"}, {word:"late", mean:"늦은"}, {word:"toy", mean:"장난감"},
        {word:"wrong", mean:"틀린"}, {word:"clothes", mean:"옷"}, {word:"turn", mean:"돌다"},
        {word:"often", mean:"자주"}, {word:"want", mean:"원하다"}, {word:"tomorrow", mean:"내일"},
        {word:"join", mean:"참여하다"}, {word:"art", mean:"예술"}, {word:"daughter", mean:"딸"},
        {word:"same", mean:"같은"}, {word:"tall", mean:"키가 큰"}, {word:"hole", mean:"구멍"},
        {word:"use", mean:"사용하다"}, {word:"newspaper", mean:"신문"}, {word:"touch", mean:"만지다"},
        {word:"husband", mean:"남편"}, {word:"field", mean:"들판"}, {word:"idea", mean:"생각"},
        {word:"win", mean:"이기다"}, {word:"swim", mean:"수영하다"}, {word:"drive", mean:"운전하다"},
        {word:"enjoy", mean:"즐기다"}, {word:"south", mean:"남쪽"}, {word:"space", mean:"우주"},
        {word:"speak", mean:"말하다"}, {word:"sea", mean:"바다"}, {word:"stair", mean:"계단"},
        {word:"island", mean:"섬"}, {word:"stupid", mean:"어리석은"}, {word:"come", mean:"오다"},
        {word:"child", mean:"아이"}, {word:"strange", mean:"이상한"}, {word:"gate", mean:"문"},
        {word:"course", mean:"과정"}, {word:"library", mean:"도서관"}, {word:"together", mean:"함께"},
        {word:"moon", mean:"달"}, {word:"much", mean:"많은"}, {word:"other", mean:"다른"},
        {word:"fight", mean:"싸우다"}, {word:"word", mean:"단어"}, {word:"country", mean:"나라"},
        {word:"holiday", mean:"휴일"}, {word:"think", mean:"생각하다"}, {word:"family", mean:"가족"},
        {word:"seat", mean:"좌석"}, {word:"key", mean:"열쇠"}, {word:"kick", mean:"차다"},
        {word:"wide", mean:"넓은"}, {word:"again", mean:"다시"}, {word:"fast", mean:"빠른"},
        {word:"study", mean:"공부하다"}, {word:"mirror", mean:"거울"}, {word:"river", mean:"강"},
        {word:"food", mean:"음식"}, {word:"big", mean:"큰"}, {word:"rich", mean:"부유한"},
        {word:"cry", mean:"울다"}, {word:"fine", mean:"좋은"}, {word:"classroom", mean:"교실"},
        {word:"table", mean:"탁자"}, {word:"call", mean:"부르다"}, {word:"hero", mean:"영웅"},
        {word:"station", mean:"역"}, {word:"spring", mean:"봄"}, {word:"expensive", mean:"비싼"},
        {word:"ready", mean:"준비된"}, {word:"hot", mean:"뜨거운"}, {word:"lunch", mean:"점심"},
        {word:"sing", mean:"노래하다"}, {word:"west", mean:"서쪽"}, {word:"act", mean:"행동하다"},
        {word:"sell", mean:"팔다"}, {word:"old", mean:"오래된"}, {word:"storm", mean:"폭풍"},
        {word:"year", mean:"년"}, {word:"rainbow", mean:"무지개"}, {word:"summer", mean:"여름"},
        {word:"night", mean:"밤"}, {word:"thunder", mean:"천둥"}, {word:"peace", mean:"평화"},
        {word:"minute", mean:"분"}, {word:"mountain", mean:"산"}, {word:"hill", mean:"언덕"},
        {word:"bathroom", mean:"화장실"}, {word:"place", mean:"장소"}, {word:"story", mean:"이야기"},
        {word:"hope", mean:"희망하다"}, {word:"listen", mean:"듣다"}, {word:"handsome", mean:"잘생긴"},
        {word:"talk", mean:"말하다"}, {word:"vase", mean:"꽃병"}, {word:"shoe", mean:"신발"},
        {word:"trip", mean:"여행"}, {word:"brush", mean:"솔"}
    ],

    // ★ 5-6학년 (고급: Day 14 ~ Day 19)
    "5-6": [
        {word:"tell", mean:"말하다"}, {word:"wise", mean:"현명한"}, {word:"map", mean:"지도"},
        {word:"puppy", mean:"강아지"}, {word:"vacation", mean:"방학"}, {word:"know", mean:"알다"},
        {word:"shop", mean:"가게"}, {word:"wall", mean:"벽"}, {word:"kid", mean:"아이"},
        {word:"dance", mean:"춤"}, {word:"part", mean:"부분"}, {word:"road", mean:"길"},
        {word:"wild", mean:"야생의"}, {word:"subway", mean:"지하철"}, {word:"dinner", mean:"저녁식사"},
        {word:"try", mean:"노력하다"}, {word:"question", mean:"질문"}, {word:"count", mean:"세다"},
        {word:"cheap", mean:"싼"}, {word:"move", mean:"움직이다"}, {word:"pass", mean:"통과하다"},
        {word:"animal", mean:"동물"}, {word:"wood", mean:"나무"}, {word:"wear", mean:"입다"},
        {word:"playground", mean:"운동장"}, {word:"see", mean:"보다"}, {word:"dead", mean:"죽은"},
        {word:"watch", mean:"지켜보다"}, {word:"ship", mean:"배"}, {word:"fat", mean:"뚱뚱한"},
        {word:"village", mean:"마을"}, {word:"luck", mean:"행운"}, {word:"season", mean:"계절"},
        {word:"kind", mean:"친절한"}, {word:"meet", mean:"만나다"}, {word:"read", mean:"읽다"},
        {word:"low", mean:"낮은"}, {word:"thin", mean:"얇은"}, {word:"poor", mean:"가난한"},
        {word:"rain", mean:"비"}, {word:"become", mean:"~이 되다"}, {word:"buy", mean:"사다"},
        {word:"grow", mean:"자라다"}, {word:"ill", mean:"아픈"}, {word:"sick", mean:"병든"},
        {word:"pretty", mean:"예쁜"}, {word:"thick", mean:"두꺼운"}, {word:"find", mean:"찾다"},
        {word:"pick", mean:"고르다"}, {word:"hate", mean:"싫어하다"}, {word:"dark", mean:"어두운"},
        {word:"never", mean:"결코 ~않다"}, {word:"show", mean:"보여주다"}, {word:"office", mean:"사무실"},
        {word:"wing", mean:"날개"}, {word:"remember", mean:"기억하다"}, {word:"dry", mean:"마른"},
        {word:"market", mean:"시장"}, {word:"hall", mean:"복도"}, {word:"people", mean:"사람들"},
        {word:"stay", mean:"머무르다"}, {word:"reporter", mean:"기자"}, {word:"freedom", mean:"자유"},
        {word:"race", mean:"경주"}, {word:"strike", mean:"치다"}, {word:"novel", mean:"소설"},
        {word:"just", mean:"단지"}, {word:"shocked", mean:"충격받은"}, {word:"wallet", mean:"지갑"},
        {word:"toilet", mean:"화장실"}, {word:"main", mean:"주요한"}, {word:"really", mean:"정말"},
        {word:"diet", mean:"식사"}, {word:"musical", mean:"뮤지컬"}, {word:"mix", mean:"섞다"},
        {word:"total", mean:"전체의"}, {word:"smile", mean:"미소"}, {word:"final", mean:"마지막의"},
        {word:"hug", mean:"포옹하다"}, {word:"later", mean:"나중에"}, {word:"miracle", mean:"기적"},
        {word:"someday", mean:"언젠가"}, {word:"arrive", mean:"도착하다"}, {word:"produce", mean:"생산하다"},
        {word:"project", mean:"계획"}, {word:"report", mean:"보고서"}, {word:"manager", mean:"관리자"},
        {word:"drop", mean:"떨어뜨리다"}, {word:"follow", mean:"따라가다"}, {word:"guide", mean:"안내하다"},
        {word:"first", mean:"첫째"}, {word:"wave", mean:"파도"}, {word:"exam", mean:"시험"},
        {word:"missing", mean:"실종된"}, {word:"either", mean:"어느 하나"}, {word:"sunlight", mean:"햇빛"},
        {word:"housework", mean:"집안일"}, {word:"pay", mean:"지불하다"}, {word:"sleep", mean:"자다"},
        {word:"stomach", mean:"위"}, {word:"slide", mean:"미끄러지다"}, {word:"exit", mean:"출구"},
        {word:"wish", mean:"소원"}, {word:"view", mean:"전망"}, {word:"heavy", mean:"무거운"},
        {word:"fantastic", mean:"환상적인"}, {word:"mystery", mean:"신비"}, {word:"rope", mean:"밧줄"},
        {word:"adventure", mean:"모험"}, {word:"closet", mean:"벽장"}, {word:"sunshine", mean:"햇살"},
        {word:"far", mean:"멀리"}, {word:"smart", mean:"똑똑한"}, {word:"smell", mean:"냄새"},
        {word:"especially", mean:"특히"}, {word:"cross", mean:"건너다"}, {word:"brave", mean:"용감한"},
        {word:"forget", mean:"잊다"}, {word:"list", mean:"목록"}, {word:"delicious", mean:"맛있는"},
        {word:"event", mean:"행사"}, {word:"practice", mean:"연습하다"}, {word:"museum", mean:"박물관"},
        {word:"background", mean:"배경"}, {word:"dentist", mean:"치과의사"}, {word:"western", mean:"서쪽의"},
        {word:"headache", mean:"두통"}, {word:"ocean", mean:"대양"}, {word:"past", mean:"과거"},
        {word:"citizen", mean:"시민"}, {word:"mushroom", mean:"버섯"}, {word:"style", mean:"스타일"},
        {word:"get", mean:"얻다"}, {word:"sunrise", mean:"일출"}, {word:"cough", mean:"기침"},
        {word:"hometown", mean:"고향"}, {word:"capital", mean:"수도"}, {word:"near", mean:"가까운"},
        {word:"natural", mean:"자연의"}, {word:"sale", mean:"판매"}, {word:"shake", mean:"흔들다"},
        {word:"laugh", mean:"웃다"}, {word:"drawer", mean:"서랍"}, {word:"noise", mean:"소음"},
        {word:"example", mean:"예시"}, {word:"point", mean:"요점"}, {word:"life", mean:"생명"},
        {word:"perfect", mean:"완벽한"}, {word:"excuse", mean:"변명"}, {word:"German", mean:"독일의"},
        {word:"central", mean:"중심의"}, {word:"fail", mean:"실패하다"}, {word:"everywhere", mean:"모든 곳"},
        {word:"meeting", mean:"회의"}, {word:"degree", mean:"도"}, {word:"shell", mean:"껍질"},
        {word:"return", mean:"돌아오다"}, {word:"university", mean:"대학교"}, {word:"grandparents", mean:"조부모"},
        {word:"magazine", mean:"잡지"}
    ],

    // ★ 중1 (심화: Day 20 ~ Day 25)
    "중1": [
        {word:"machine", mean:"기계"}, {word:"purse", mean:"지갑"}, {word:"hurry", mean:"서두르다"},
        {word:"tough", mean:"거친"}, {word:"guard", mean:"경비원"}, {word:"nature", mean:"자연"},
        {word:"full", mean:"가득 찬"}, {word:"suddenly", mean:"갑자기"}, {word:"design", mean:"디자인"},
        {word:"health", mean:"건강"}, {word:"send", mean:"보내다"}, {word:"classmate", mean:"반 친구"},
        {word:"artwork", mean:"예술작품"}, {word:"both", mean:"둘 다"}, {word:"ahead", mean:"앞에"},
        {word:"break", mean:"깨다"}, {word:"finally", mean:"마침내"}, {word:"sit", mean:"앉다"},
        {word:"lonely", mean:"외로운"}, {word:"live", mean:"살다"}, {word:"possible", mean:"가능한"},
        {word:"believe", mean:"믿다"}, {word:"store", mean:"가게"}, {word:"while", mean:"~동안"},
        {word:"inside", mean:"안에"}, {word:"dislike", mean:"싫어하다"}, {word:"coast", mean:"해안"},
        {word:"without", mean:"~없이"}, {word:"finish", mean:"끝내다"}, {word:"only", mean:"오직"},
        {word:"danger", mean:"위험"}, {word:"ask", mean:"묻다"}, {word:"honey", mean:"꿀"},
        {word:"sunset", mean:"일몰"}, {word:"person", mean:"사람"}, {word:"gentleman", mean:"신사"},
        {word:"weed", mean:"잡초"}, {word:"smoke", mean:"연기"}, {word:"press", mean:"누르다"},
        {word:"worry", mean:"걱정하다"}, {word:"ghost", mean:"유령"}, {word:"nickname", mean:"별명"},
        {word:"surprised", mean:"놀란"}, {word:"sad", mean:"슬픈"}, {word:"solar", mean:"태양의"},
        {word:"slim", mean:"날씬한"}, {word:"seafood", mean:"해산물"}, {word:"dive", mean:"다이빙하다"},
        {word:"rest", mean:"휴식"}, {word:"sweet", mean:"달콤한"}, {word:"lock", mean:"잠그다"},
        {word:"among", mean:"~사이에"}, {word:"build", mean:"짓다"}, {word:"bike", mean:"자전거"},
        {word:"price", mean:"가격"}, {word:"sock", mean:"양말"}, {word:"insect", mean:"곤충"},
        {word:"snow", mean:"눈"}, {word:"bright", mean:"밝은"}, {word:"exercise", mean:"운동"},
        {word:"charming", mean:"매력적인"}, {word:"beat", mean:"이기다"}, {word:"agree", mean:"동의하다"},
        {word:"supper", mean:"저녁식사"}, {word:"garbage", mean:"쓰레기"}, {word:"meal", mean:"식사"},
        {word:"simple", mean:"간단한"}, {word:"plate", mean:"접시"}, {word:"hike", mean:"하이킹하다"},
        {word:"surprise", mean:"놀라게 하다"}, {word:"tour", mean:"여행"}, {word:"powerful", mean:"강력한"},
        {word:"add", mean:"더하다"}, {word:"role", mean:"역할"}, {word:"Italian", mean:"이탈리아의"},
        {word:"interest", mean:"흥미"}, {word:"introduce", mean:"소개하다"}, {word:"pull", mean:"당기다"},
        {word:"member", mean:"회원"}, {word:"nephew", mean:"조카"}, {word:"loud", mean:"시끄러운"},
        {word:"once", mean:"한 번"}, {word:"decorate", mean:"장식하다"}, {word:"college", mean:"대학"},
        {word:"curly", mean:"곱슬곱슬한"}, {word:"mobile", mean:"이동하는"}, {word:"slow", mean:"느린"},
        {word:"chat", mean:"수다떨다"}, {word:"elementary", mean:"초등의"}, {word:"fresh", mean:"신선한"},
        {word:"enough", mean:"충분한"}, {word:"steam", mean:"증기"}, {word:"some", mean:"약간의"},
        {word:"whole", mean:"전체의"}, {word:"begin", mean:"시작하다"}, {word:"tourist", mean:"관광객"},
        {word:"item", mean:"품목"}, {word:"pot", mean:"냄비"}, {word:"able", mean:"할 수 있는"},
        {word:"stage", mean:"무대"}, {word:"hunt", mean:"사냥하다"}, {word:"relax", mean:"쉬다"},
        {word:"goal", mean:"목표"}, {word:"fever", mean:"열"}, {word:"gesture", mean:"몸짓"},
        {word:"speech", mean:"연설"}, {word:"easy", mean:"쉬운"}, {word:"graph", mean:"그래프"},
        {word:"push", mean:"밀다"}, {word:"sample", mean:"견본"}, {word:"another", mean:"다른"},
        {word:"most", mean:"대부분"}, {word:"nobody", mean:"아무도"}, {word:"forever", mean:"영원히"},
        {word:"answer", mean:"대답"}, {word:"important", mean:"중요한"}, {word:"Europe", mean:"유럽"},
        {word:"pair", mean:"한 쌍"}, {word:"deeply", mean:"깊이"}, {word:"save", mean:"구하다"}
    ]
};